/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.9-rc-2/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    repositories {
        // 使用阿里云镜像替换gradlePluginPortal
        maven { url = uri("https://maven.aliyun.com/repository/gradle-plugin") }
        // 如果阿里云镜像不可用，回退到原始仓库
        gradlePluginPortal()
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

dependencyResolutionManagement {
    repositories {
        // 使用阿里云镜像替换Maven Central
        maven { url = uri("https://maven.aliyun.com/repository/public") }
        maven { url = uri("https://maven.aliyun.com/repository/google") }
        // 如果阿里云镜像不可用，回退到原始仓库
        mavenCentral()
        google()
    }
}

rootProject.name = "VirtualCamera"
include("lib")