name: VirtualCamera
version: 1.0.0
main: cn.popcraft.VirtualCameraPlugin
api-version: 1.16
description: 一个虚拟相机插件，用于创建电影效果和场景展示
author: PopCraft

commands:
  camera:
    description: 虚拟相机主命令
    usage: /camera <enter|exit|save|load|delete|list|play|stop|help>
    aliases: [cam, vcam]
  vcam:
    description: 虚拟相机主命令 (别名)
    usage: /vcam <enter|exit|save|load|delete|list|play|stop|help>
    aliases: [cam, camera]

permissions:
  virtualcamera.use:
    description: 允许使用虚拟相机基本功能
    default: op
  virtualcamera.preset.save:
    description: 允许保存相机预设
    default: op
  virtualcamera.preset.load:
    description: 允许加载相机预设
    default: op
  virtualcamera.preset.delete:
    description: 允许删除相机预设
    default: op
  virtualcamera.preset.list:
    description: 允许列出相机预设
    default: op
  virtualcamera.preset.create:
    description: 允许创建相机预设
    default: op
  virtualcamera.preset.edit:
    description: 允许编辑相机预设
    default: op
  virtualcamera.sequence.play:
    description: 允许播放相机序列
    default: op
  virtualcamera.sequence.stop:
    description: 允许停止相机序列
    default: op
  virtualcamera.random.start:
    description: 允许开始随机切换
    default: op
  virtualcamera.random.stop:
    description: 允许停止随机切换
    default: op
  virtualcamera.random.add:
    description: 允许添加预设到随机切换池
    default: op
  virtualcamera.random.remove:
    description: 允许从随机切换池移除预设
    default: op
  virtualcamera.random.list:
    description: 允许列出随机切换池
    default: op